<?php
return array (
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜影音',
    'des' => 'xigua.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '450',
    'tip' => '<a href="http://union.maccms.com/html/xigua.html" target="_blank">需要下载西瓜影音播放器</a>',
    'id' => 'xigua',
  ),
  'xfplay' => 
  array (
    'status' => '1',
    'from' => 'xfplay',
    'show' => '先锋影音',
    'des' => 'xfplay.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '449',
    'tip' => '<a href="http://union.maccms.com/html/xfplay.html" target="_blank">需要下载先锋影音播放器</a>',
    'id' => 'xfplay',
  ),
  'jjvod' => 
  array (
    'status' => '1',
    'from' => 'jjvod',
    'show' => '吉吉影音',
    'des' => 'jijizy.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '448',
    'tip' => '<a href="http://union.maccms.com/html/jjvod.html" target="_blank">需要下载吉吉影音播放器</a>',
    'id' => 'jjvod',
  ),
  'fvod' => 
  array (
    'status' => '1',
    'from' => 'fvod',
    'show' => '肥佬影音',
    'des' => 'www.feilao.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '447',
    'tip' => '<a href="http://union.maccms.com/html/fvod.html" target="_blank">需要下载肥佬影音播放器</a>',
    'id' => 'fvod',
  ),
  'ffhd' => 
  array (
    'status' => '1',
    'from' => 'ffhd',
    'show' => '非凡影音',
    'des' => 'www.feifan.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '446',
    'tip' => '<a href="http://union.maccms.com/html/ffhd.html" target="_blank">需要下载非凡影音播放器</a>',
    'id' => 'ffhd',
  ),
  'niba' => 
  array (
    'status' => '1',
    'from' => 'niba',
    'show' => '泥巴影音',
    'des' => 'www.nbplay.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '445',
    'tip' => '<a href="http://union.maccms.com/html/niba.html" target="_blank">需要下载泥巴影音播放器</a>',
    'id' => 'niba',
  ),
  'kkhd' => 
  array (
    'status' => '1',
    'from' => 'kkhd',
    'show' => '可可影音',
    'des' => 'www.kekeplay.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '444',
    'tip' => '<a href="http://union.maccms.com/html/kkhd.html" target="_blank">需要下载可可影音播放器</a>',
    'id' => 'kkhd',
  ),
  'kankan' => 
  array (
    'status' => '1',
    'from' => 'kankan',
    'show' => '迅雷看看',
    'des' => 'www.kankan.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '442',
    'tip' => '<a href="http://union.maccms.com/html/kankan.html" target="_blank">需要下载迅雷看看播放器</a>',
    'id' => 'kankan',
  ),
  'gvod' => 
  array (
    'status' => '1',
    'from' => 'gvod',
    'show' => '迅播gvod',
    'des' => 'gvod.xunlei.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '410',
    'tip' => '<a href="http://union.maccms.com/html/gvod.html" target="_blank">需要下载讯播GVOD播放器</a>',
    'id' => 'gvod',
  ),
  'cool' => 
  array (
    'status' => '1',
    'from' => 'cool',
    'show' => '酷播cool',
    'des' => 'mycoolplay.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '409',
    'tip' => '<a href="http://union.maccms.com/html/cool.html" target="_blank">需要下载酷播播放器</a>',
    'id' => 'cool',
  ),
  'qvod' => 
  array (
    'status' => '1',
    'from' => 'qvod',
    'show' => '快播qvod',
    'des' => 'qvod.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '408',
    'tip' => '<a href="http://union.maccms.com/html/qvod.html" target="_blank">需要下载快播QVOD播放器</a>',
    'id' => 'qvod',
  ),
  'baidu' => 
  array (
    'status' => '1',
    'from' => 'baidu',
    'show' => '百度影音',
    'des' => 'play.baidu.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '407',
    'tip' => '<a href="http://union.maccms.com/html/baidu.html" target="_blank">需要下载百度影音播放器</a>',
    'id' => 'baidu',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => 'youku.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '390',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  56 => 
  array (
    'status' => '1',
    'from' => '56',
    'show' => '我乐视频',
    'des' => '56.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '380',
    'tip' => '无需安装任何插件',
    'id' => '56',
  ),
  'tudou' => 
  array (
    'status' => '1',
    'from' => 'tudou',
    'show' => '土豆视频',
    'des' => 'tudou.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '370',
    'tip' => '无需安装任何插件',
    'id' => 'tudou',
  ),
  'ku6' => 
  array (
    'status' => '1',
    'from' => 'ku6',
    'show' => '酷6视频',
    'des' => 'ku6.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '360',
    'tip' => '无需安装任何插件',
    'id' => 'ku6',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => 'v.qq.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '350',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => 'v.sohu.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '340',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'joy' => 
  array (
    'status' => '1',
    'from' => 'joy',
    'show' => '激动网',
    'des' => 'joy.cn',
    'ps' => '1',
    'parse' => '',
    'sort' => '330',
    'tip' => '无需安装任何插件',
    'id' => 'joy',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => 'qiyi.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '320',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => 'letv.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '310',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '300',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果tv',
    'des' => 'mgtv.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '290',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'from' => 'wasu',
    'show' => '华数tv',
    'des' => 'wasu.cn',
    'ps' => '1',
    'parse' => '',
    'sort' => '280',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'tudouhd' => 
  array (
    'status' => '1',
    'from' => 'tudouhd',
    'show' => '土豆(高清)',
    'des' => 'hd.tudou.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '260',
    'tip' => '无需安装任何插件',
    'id' => 'tudouhd',
  ),
  'sohuhd' => 
  array (
    'status' => '1',
    'from' => 'sohuhd',
    'show' => '搜狐(高清)',
    'des' => 'tv.sohu.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '250',
    'tip' => '无需安装任何插件',
    'id' => 'sohuhd',
  ),
  'ku6hd' => 
  array (
    'status' => '1',
    'from' => 'ku6hd',
    'show' => '酷6(高清)',
    'des' => 'hd.ku6.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '240',
    'tip' => '无需安装任何插件',
    'id' => 'ku6hd',
  ),
  'sinahd' => 
  array (
    'status' => '1',
    'from' => 'sinahd',
    'show' => '新浪(高清)',
    'des' => 'video.sina.com.cn',
    'ps' => '1',
    'parse' => '',
    'sort' => '220',
    'tip' => '无需安装任何插件',
    'id' => 'sinahd',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => 'pptv.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '210',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'fantasy' => 
  array (
    'status' => '1',
    'from' => 'fantasy',
    'show' => '范特西云视频',
    'des' => '范特西',
    'ps' => '1',
    'parse' => '',
    'sort' => '200',
    'tip' => '无需安装任何插件',
    'id' => 'fantasy',
  ),
  'real' => 
  array (
    'status' => '1',
    'from' => 'real',
    'show' => 'RealPlaer播放器',
    'des' => 'real.cn',
    'ps' => '1',
    'parse' => '',
    'sort' => '120',
    'tip' => '需要电脑安装RealPlayer播放器',
    'id' => 'real',
  ),
  'media' => 
  array (
    'status' => '1',
    'from' => 'media',
    'show' => 'MediaPlayer播放器',
    'des' => 'mediaplayer',
    'ps' => '1',
    'parse' => '',
    'sort' => '110',
    'tip' => '无需安装任何插件',
    'id' => 'media',
  ),
  'ckplayer' => 
  array (
    'status' => '1',
    'from' => 'ckplayer',
    'show' => 'CkPlayer-H5播放器',
    'des' => 'ckplayer.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '14',
    'tip' => '无需安装任何插件',
    'id' => 'ckplayer',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'ps' => '1',
    'parse' => '',
    'sort' => '13',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'H5自带解析',
    'des' => 'videojj.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '12',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'swf' => 
  array (
    'status' => '1',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'ps' => '1',
    'parse' => '',
    'sort' => '11',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '1',
    'parse' => '',
    'sort' => '10',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '1',
    'parse' => '',
    'sort' => '9',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
);
?>